<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7-server:
    roles:
     - server
     - default
     - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

  el7-ldap:
    roles:
      - ldap
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    #need to get simp_ppolicy rpm.
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE


  el8-server:
    roles:
      - server
      - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: <%= hypervisor %>

  el8-ldap:
    roles:
      - 389ds
      - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  synced_folder : disabled
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
